export const TOKEN_STORAGE_KEY = "JOYFUL_AUTH_TOKEN";
export const SIGNATURE_STORAGE_KEY = "JOYFUL_SIGNATURE_KEY";
export const LOGOUT_REASON_STORAGE_KEY = "JOYFUL_LOGOUT_REASON";
export const REMEMBER_CREDENTIALS_KEY = "JOYFUL_REMEMBER_LOGIN";
